version: '3'

tasks:
  dev:
    deps: [templ]
    cmds:
      - task --parallel templ-watch server-watch

  server-watch:
    deps: [templ]
    cmds:
      - go tool air -c .air.toml

  build:
    deps: [sqlc, templ]
    cmds:
      - go build ./cmd/server

  migrate:
    cmds:
      - go run ./cmd/server -migrate-only

  seed:
    cmds:
      - go run ./cmd/server -seed-only

  reset-read-models:
    cmds:
      - go run ./cmd/server -reset-read-models

  templ:
    sources:
      - "**/*.templ"
    generates:
      - "**/*_templ.go"
    cmds:
      - go tool templ generate

  templ-watch:
    cmds:
      - go tool templ generate -watch

  sqlc:
    sources:
      - sqlc.yaml
      - queries/**/*.sql
      - migrations/**/*.sql
    generates:
      - internal/dbsql/**/*.go
    cmds:
      - GOBIN="{{.ROOT_DIR}}/.bin" go install github.com/delaneyj/toolbelt/sqlc-gen-zombiezen
      - PATH="{{.ROOT_DIR}}/.bin:$PATH" sqlc generate