INSERT INTO
  students (first_name, chosen_name, last_name, grade, homeroom, case_manager)
VALUES
  ('Harrison', '', 'Dahlburg-Nuorala', 5, 'ellen', 'Hannah'),
  ('Eleanor', 'Ella', 'Cotner', 5, 'ellen', 'Jordyn'),
  ('Elijah', '', 'Jones', 5, 'ellen', 'Jordyn'),
  ('Elliott', '', 'Griffin', 6, 'ellen', 'Jordyn'),
  ('Jake', '', 'Sauer', 5, 'ellen', 'Jordyn'),
  ('Katt', '', 'Mass', 6, 'ellen', 'Jordyn'),
  ('Noelle', '', 'Hardisty', 6, 'ellen', 'Jordyn'),
  ('Silas', '', 'Bohrman', 6, 'ellen', 'Jordyn'),
  ('Vincent', '', 'Wilburn', 5, 'ellen', 'Jordyn'),
  ('Anisa', 'Fern', 'Voerding', 6, 'scott', '!uke'),
  ('Elliott', '', 'Honken', 6, 'scott', '!uke'),
  ('Gionni', 'Gio', 'Barber', 5, 'scott', '!uke'),
  ('Henry', '', 'Hart', 6, 'scott', '!uke'),
  ('Oliver', '', 'Schuett', 5, 'scott', '!uke'),
  ('Solomon', '', 'Guntlisbergen', 5, 'scott', '!uke'),
  ('Wren', '', 'Welderber', 5, 'scott', '!uke'),
  ('Xavier', '', 'Johnson', 6, 'scott', '!uke'),
  ('Jemma', '', 'Berry', 5, 'scott', 'Carly'),
  ('Azalea', '', 'Sullivan-Thigpen', 6, 'scott', 'Jordyn'),
  ('Lucas', '', 'Tanner', 5, 'scott', 'Jordyn'),
  ('Mae', '', 'Davis', 6, 'scott', 'Jordyn'),
  ('Mila', '', 'Thompson', 6, 'scott', 'Jordyn'),
  ('River', '', 'Honsey', 6, 'scott', 'Jordyn'),
  ('Elizabeth', '', 'Evans', 5, 'sophie', '!uke'),
  ('Fox', '', 'Dahlton', 6, 'sophie', '!uke'),
  ('Keegan', '', 'Stensland', 5, 'sophie', '!uke'),
  ('Livian', 'Livi', 'King', 6, 'sophie', '!uke'),
  ('Naomi', 'Olive', 'Monn', 5, 'sophie', '!uke'),
  ('Terrell', '', 'King-Adams', 6, 'sophie', '!uke'),
  ('Theo', '', 'Heitland', 5, 'sophie', '!uke'),
  ('Xavier', '', 'Morales-Clark', 5, 'sophie', 'Hannah'),
  ('Seville', '', 'Love', 6, 'sophie', '!uke');
