INSERT INTO
  students (first_name, chosen_name, last_name, grade, homeroom, case_manager, last_event_commit_position, last_event_prepare_position)
VALUES
  ('Harrison', null, 'Dahlburg-Nuorala', 5, 'ellen', 'Hannah', 0, 0),
  ('Eleanor', 'Ella', 'Cotner', 5, 'ellen', 'Jordyn', 0, 0),
  ('Elijah', null, 'Jones', 5, 'ellen', 'Jordyn', 0, 0),
  ('Elliott', null, 'Griffin', 6, 'ellen', 'Jordyn', 0, 0),
  ('Jake', null, 'Sauer', 5, 'ellen', 'Jordyn', 0, 0),
  ('Katt', null, 'Mass', 6, 'ellen', 'Jordyn', 0, 0),
  ('Noelle', null, 'Hardisty', 6, 'ellen', 'Jordyn', 0, 0),
  ('Silas', null, 'Bohrman', 6, 'ellen', 'Jordyn', 0, 0),
  ('Vincent', null, 'Wilburn', 5, 'ellen', 'Jordyn', 0, 0),
  ('Anisa', 'Fern', 'Voerding', 6, 'scott', '!uke', 0, 0),
  ('Elliott', null, 'Honken', 6, 'scott', '!uke', 0, 0),
  ('Gionni', 'Gio', 'Barber', 5, 'scott', '!uke', 0, 0),
  ('Henry', null, 'Hart', 6, 'scott', '!uke', 0, 0),
  ('Oliver', null, 'Schuett', 5, 'scott', '!uke', 0, 0),
  ('Solomon', null, 'Guntlisbergen', 5, 'scott', '!uke', 0, 0),
  ('Wren', null, 'Welderber', 5, 'scott', '!uke', 0, 0),
  ('Xavier', null, 'Johnson', 6, 'scott', '!uke', 0, 0),
  ('Jemma', null, 'Berry', 5, 'scott', 'Carly', 0, 0),
  ('Azalea', null, 'Sullivan-Thigpen', 6, 'scott', 'Jordyn', 0, 0),
  ('Lucas', null, 'Tanner', 5, 'scott', 'Jordyn', 0, 0),
  ('Mae', null, 'Davis', 6, 'scott', 'Jordyn', 0, 0),
  ('Mila', null, 'Thompson', 6, 'scott', 'Jordyn', 0, 0),
  ('River', null, 'Honsey', 6, 'scott', 'Jordyn', 0, 0),
  ('Elizabeth', null, 'Evans', 5, 'sophie', '!uke', 0, 0),
  ('Fox', null, 'Dahlton', 6, 'sophie', '!uke', 0, 0),
  ('Keegan', null, 'Stensland', 5, 'sophie', '!uke', 0, 0),
  ('Livian', 'Livi', 'King', 6, 'sophie', '!uke', 0, 0),
  ('Naomi', 'Olive', 'Monn', 5, 'sophie', '!uke', 0, 0),
  ('Terrell', null, 'King-Adams', 6, 'sophie', '!uke', 0, 0),
  ('Theo', null, 'Heitland', 5, 'sophie', '!uke', 0, 0),
  ('Xavier', null, 'Morales-Clark', 5, 'sophie', 'Hannah', 0, 0),
  ('Seville', null, 'Love', 6, 'sophie', '!uke', 0, 0);
