// Code generated by "sqlc-gen-zombiezen". DO NOT EDIT.

package dbsql

import (
	"fmt"
	"zombiezen.com/go/sqlite"
)

type AddIeptoStudentParams struct {
	Id                       string `json:"id"`
	StudentId                string `json:"student_id"`
	PlanManagerId            string `json:"plan_manager_id"`
	Disability1              int64  `json:"disability_1"`
	Disability2              int64  `json:"disability_2"`
	FederalSetting           int64  `json:"federal_setting"`
	MeetingDate              string `json:"meeting_date"`
	IepDueDate               string `json:"iep_due_date"`
	LastEvalDate             string `json:"last_eval_date"`
	EvalDueDate              string `json:"eval_due_date"`
	AmendedDate              string `json:"amended_date"`
	IepType                  int64  `json:"iep_type"`
	SpecialTransportation    int64  `json:"special_transportation"`
	LastEventCommitPosition  int64  `json:"last_event_commit_position"`
	LastEventPreparePosition int64  `json:"last_event_prepare_position"`
	CreatedAt                string `json:"created_at"`
}

type AddIeptoStudentStmt struct {
	conn      *sqlite.Conn
	stmt      *sqlite.Stmt
	querySQL  string
	hasSlices bool
}

func AddIeptoStudent(tx *sqlite.Conn) *AddIeptoStudentStmt {
	const querySQL = `
INSERT INTO student_ieps (
	id,
	student_id,
	plan_manager_id,
	disability_1,
	disability_2,
	federal_setting,
	meeting_date,
	iep_due_date,
	last_eval_date,
	eval_due_date,
	amended_date,
	iep_type,
	special_transportation,
	last_event_commit_position,
	last_event_prepare_position,
	created_at,
	updated_at
)
VALUES (
	?1,
	?2,
	?3,
	?4,
	?5,
	?6,
	?7,
	?8,
	?9,
	?10,
	?11,
	?12,
	?13,
	?14,
	?15,
	?16,
	?16
)
ON CONFLICT (id) DO NOTHING
    `

	ps := &AddIeptoStudentStmt{
		conn:      tx,
		querySQL:  querySQL,
		hasSlices: false,
	}

	if !ps.hasSlices {
		ps.stmt = tx.Prep(querySQL)
	}

	return ps
}

func (ps *AddIeptoStudentStmt) Run(
	params AddIeptoStudentParams,
) (
	err error,
) {
	querySQL := ps.querySQL

	var stmt *sqlite.Stmt
	if ps.hasSlices {
		stmt = ps.conn.Prep(querySQL)
	} else {
		stmt = ps.stmt
	}

	defer func() {
		_ = stmt.ClearBindings()
		_ = stmt.Reset()
	}()

	bindIndex := 1
	// Bind parameters
	stmt.BindText(bindIndex, params.Id)

	bindIndex++
	stmt.BindText(bindIndex, params.StudentId)

	bindIndex++
	stmt.BindText(bindIndex, params.PlanManagerId)

	bindIndex++
	stmt.BindInt64(bindIndex, params.Disability1)

	bindIndex++
	stmt.BindInt64(bindIndex, params.Disability2)

	bindIndex++
	stmt.BindInt64(bindIndex, params.FederalSetting)

	bindIndex++
	stmt.BindText(bindIndex, params.MeetingDate)

	bindIndex++
	stmt.BindText(bindIndex, params.IepDueDate)

	bindIndex++
	stmt.BindText(bindIndex, params.LastEvalDate)

	bindIndex++
	stmt.BindText(bindIndex, params.EvalDueDate)

	bindIndex++
	stmt.BindText(bindIndex, params.AmendedDate)

	bindIndex++
	stmt.BindInt64(bindIndex, params.IepType)

	bindIndex++
	stmt.BindInt64(bindIndex, params.SpecialTransportation)

	bindIndex++
	stmt.BindInt64(bindIndex, params.LastEventCommitPosition)

	bindIndex++
	stmt.BindInt64(bindIndex, params.LastEventPreparePosition)

	bindIndex++
	stmt.BindText(bindIndex, params.CreatedAt)

	bindIndex++

	// Execute the query
	if _, err := stmt.Step(); err != nil {
		return fmt.Errorf("failed to execute addieptostudent SQL: %w", err)
	}

	return nil
}

func OnceAddIeptoStudent(
	tx *sqlite.Conn,
	params AddIeptoStudentParams,
) (
	err error,
) {
	ps := AddIeptoStudent(tx)

	return ps.Run(
		params,
	)
}
