// Code generated by "sqlc-gen-zombiezen". DO NOT EDIT.

package dbsql

import (
	"fmt"
	"zombiezen.com/go/sqlite"
)

type AddRoleToEducatorParams struct {
	EducatorId               string `json:"educator_id"`
	Role                     string `json:"role"`
	LastEventCommitPosition  int64  `json:"last_event_commit_position"`
	LastEventPreparePosition int64  `json:"last_event_prepare_position"`
	CreatedAt                string `json:"created_at"`
}

type AddRoleToEducatorStmt struct {
	conn      *sqlite.Conn
	stmt      *sqlite.Stmt
	querySQL  string
	hasSlices bool
}

func AddRoleToEducator(tx *sqlite.Conn) *AddRoleToEducatorStmt {
	const querySQL = `
INSERT INTO educator_roles ( 
	educator_id, 
	role,
	last_event_commit_position, 
	last_event_prepare_position,
	created_at, 
	updated_at
)
VALUES (
	?1, 
	?2,
	?3, 
	?4,
	?5, 
	?5
)
ON CONFLICT (educator_id, role) DO NOTHING
    `

	ps := &AddRoleToEducatorStmt{
		conn:      tx,
		querySQL:  querySQL,
		hasSlices: false,
	}

	if !ps.hasSlices {
		ps.stmt = tx.Prep(querySQL)
	}

	return ps
}

func (ps *AddRoleToEducatorStmt) Run(
	params AddRoleToEducatorParams,
) (
	err error,
) {
	querySQL := ps.querySQL

	var stmt *sqlite.Stmt
	if ps.hasSlices {
		stmt = ps.conn.Prep(querySQL)
	} else {
		stmt = ps.stmt
	}

	defer func() {
		_ = stmt.ClearBindings()
		_ = stmt.Reset()
	}()

	bindIndex := 1
	// Bind parameters
	stmt.BindText(bindIndex, params.EducatorId)

	bindIndex++
	stmt.BindText(bindIndex, params.Role)

	bindIndex++
	stmt.BindInt64(bindIndex, params.LastEventCommitPosition)

	bindIndex++
	stmt.BindInt64(bindIndex, params.LastEventPreparePosition)

	bindIndex++
	stmt.BindText(bindIndex, params.CreatedAt)

	bindIndex++

	// Execute the query
	if _, err := stmt.Step(); err != nil {
		return fmt.Errorf("failed to execute addroletoeducator SQL: %w", err)
	}

	return nil
}

func OnceAddRoleToEducator(
	tx *sqlite.Conn,
	params AddRoleToEducatorParams,
) (
	err error,
) {
	ps := AddRoleToEducator(tx)

	return ps.Run(
		params,
	)
}
