// Code generated by "sqlc-gen-zombiezen". DO NOT EDIT.

package dbsql

import (
	"fmt"
	"zombiezen.com/go/sqlite"
)

type CreateStudentParams struct {
	Id                       string `json:"id"`
	MarssId                  string `json:"marss_id"`
	GivenName                string `json:"given_name"`
	ChosenName               string `json:"chosen_name"`
	FamilyName               string `json:"family_name"`
	Email                    string `json:"email"`
	Username                 string `json:"username"`
	Grade                    int64  `json:"grade"`
	Homeroom                 string `json:"homeroom"`
	CaseManager              string `json:"case_manager"`
	LastEventCommitPosition  int64  `json:"last_event_commit_position"`
	LastEventPreparePosition int64  `json:"last_event_prepare_position"`
	CreatedAt                string `json:"created_at"`
}

type CreateStudentStmt struct {
	conn      *sqlite.Conn
	stmt      *sqlite.Stmt
	querySQL  string
	hasSlices bool
}

func CreateStudent(tx *sqlite.Conn) *CreateStudentStmt {
	const querySQL = `
INSERT INTO students (
	id, 
	marss_id,
	given_name, 
	chosen_name, 
	family_name, 
	email,
	username,
	grade, 
	homeroom, 
	case_manager, 
	last_event_commit_position,
	last_event_prepare_position,
	created_at, 
	updated_at
)
VALUES (
	?1, 
	?2,
	?3, 
	?4, 
	?5, 
	?6,
	?7,
	?8, 
	?9, 
	?10, 
	?11, 
	?12,
	?13, 
	?13
)
ON CONFLICT (id) DO NOTHING
    `

	ps := &CreateStudentStmt{
		conn:      tx,
		querySQL:  querySQL,
		hasSlices: false,
	}

	if !ps.hasSlices {
		ps.stmt = tx.Prep(querySQL)
	}

	return ps
}

func (ps *CreateStudentStmt) Run(
	params CreateStudentParams,
) (
	err error,
) {
	querySQL := ps.querySQL

	var stmt *sqlite.Stmt
	if ps.hasSlices {
		stmt = ps.conn.Prep(querySQL)
	} else {
		stmt = ps.stmt
	}

	defer func() {
		_ = stmt.ClearBindings()
		_ = stmt.Reset()
	}()

	bindIndex := 1
	// Bind parameters
	stmt.BindText(bindIndex, params.Id)

	bindIndex++
	stmt.BindText(bindIndex, params.MarssId)

	bindIndex++
	stmt.BindText(bindIndex, params.GivenName)

	bindIndex++
	stmt.BindText(bindIndex, params.ChosenName)

	bindIndex++
	stmt.BindText(bindIndex, params.FamilyName)

	bindIndex++
	stmt.BindText(bindIndex, params.Email)

	bindIndex++
	stmt.BindText(bindIndex, params.Username)

	bindIndex++
	stmt.BindInt64(bindIndex, params.Grade)

	bindIndex++
	stmt.BindText(bindIndex, params.Homeroom)

	bindIndex++
	stmt.BindText(bindIndex, params.CaseManager)

	bindIndex++
	stmt.BindInt64(bindIndex, params.LastEventCommitPosition)

	bindIndex++
	stmt.BindInt64(bindIndex, params.LastEventPreparePosition)

	bindIndex++
	stmt.BindText(bindIndex, params.CreatedAt)

	bindIndex++

	// Execute the query
	if _, err := stmt.Step(); err != nil {
		return fmt.Errorf("failed to execute createstudent SQL: %w", err)
	}

	return nil
}

func OnceCreateStudent(
	tx *sqlite.Conn,
	params CreateStudentParams,
) (
	err error,
) {
	ps := CreateStudent(tx)

	return ps.Run(
		params,
	)
}
