// Code generated by "sqlc-gen-zombiezen". DO NOT EDIT.

package dbsql

import (
	"fmt"
	"zombiezen.com/go/sqlite"
)

type CreateTeacherParams struct {
	Id                       string  `json:"id"`
	GivenName                string  `json:"given_name"`
	ChosenName               *string `json:"chosen_name"`
	FamilyName               string  `json:"family_name"`
	CreatedAt                string  `json:"created_at"`
	LastEventCommitPosition  int64   `json:"last_event_commit_position"`
	LastEventPreparePosition int64   `json:"last_event_prepare_position"`
}

type CreateTeacherStmt struct {
	conn      *sqlite.Conn
	stmt      *sqlite.Stmt
	querySQL  string
	hasSlices bool
}

func CreateTeacher(tx *sqlite.Conn) *CreateTeacherStmt {
	const querySQL = `
INSERT INTO teachers (id, given_name, chosen_name, family_name, created_at, updated_at, last_event_commit_position, last_event_prepare_position)
VALUES (?1, ?2, ?3, ?4, ?5, ?5, ?6, ?7)
ON CONFLICT (id) DO NOTHING
    `

	ps := &CreateTeacherStmt{
		conn:      tx,
		querySQL:  querySQL,
		hasSlices: false,
	}

	if !ps.hasSlices {
		ps.stmt = tx.Prep(querySQL)
	}

	return ps
}

func (ps *CreateTeacherStmt) Run(
	params CreateTeacherParams,
) (
	err error,
) {
	querySQL := ps.querySQL

	var stmt *sqlite.Stmt
	if ps.hasSlices {
		stmt = ps.conn.Prep(querySQL)
	} else {
		stmt = ps.stmt
	}

	defer func() {
		_ = stmt.ClearBindings()
		_ = stmt.Reset()
	}()

	bindIndex := 1
	// Bind parameters
	stmt.BindText(bindIndex, params.Id)

	bindIndex++
	stmt.BindText(bindIndex, params.GivenName)

	bindIndex++
	if params.ChosenName == nil {
		stmt.BindNull(bindIndex)
	} else {
		stmt.BindText(bindIndex, *params.ChosenName)

	}
	bindIndex++
	stmt.BindText(bindIndex, params.FamilyName)

	bindIndex++
	stmt.BindText(bindIndex, params.CreatedAt)

	bindIndex++
	stmt.BindInt64(bindIndex, params.LastEventCommitPosition)

	bindIndex++
	stmt.BindInt64(bindIndex, params.LastEventPreparePosition)

	bindIndex++

	// Execute the query
	if _, err := stmt.Step(); err != nil {
		return fmt.Errorf("failed to execute createteacher SQL: %w", err)
	}

	return nil
}

func OnceCreateTeacher(
	tx *sqlite.Conn,
	params CreateTeacherParams,
) (
	err error,
) {
	ps := CreateTeacher(tx)

	return ps.Run(
		params,
	)
}
