// Code generated by "sqlc-gen-zombiezen". DO NOT EDIT.

package dbsql

import (
	"fmt"
	"zombiezen.com/go/sqlite"
)

type CreateStudentServiceParams struct {
	Id              string  `json:"id"`
	StudentId       string  `json:"student_id"`
	ServiceType     string  `json:"service_type"`
	IndirectMinutes *int64  `json:"indirect_minutes"`
	DirectMinutes   *int64  `json:"direct_minutes"`
	FrequencyCount  *int64  `json:"frequency_count"`
	FrequencyType   *string `json:"frequency_type"`
	Location        *string `json:"location"`
	StartDate       *string `json:"start_date"`
	EndDate         *string `json:"end_date"`
	Provider        *string `json:"provider"`
	CreatedAt       string  `json:"created_at"`
}

type CreateStudentServiceStmt struct {
	conn      *sqlite.Conn
	stmt      *sqlite.Stmt
	querySQL  string
	hasSlices bool
}

func CreateStudentService(tx *sqlite.Conn) *CreateStudentServiceStmt {
	const querySQL = `
INSERT INTO student_services (
	id, 
	student_id, 
	service_type, 
	indirect_minutes,
	direct_minutes,
	frequency_count,
	frequency_type,
	location,
	start_date,
	end_date,
	provider,
	created_at, 
	updated_at
)
VALUES (
	?1, 
	?2, 
	?3, 
	?4,
	?5,
	?6,
	?7,
	?8,
	?9,
	?10,
	?11,
	?12, 
	?12
)
ON CONFLICT (id) DO NOTHING
    `

	ps := &CreateStudentServiceStmt{
		conn:      tx,
		querySQL:  querySQL,
		hasSlices: false,
	}

	if !ps.hasSlices {
		ps.stmt = tx.Prep(querySQL)
	}

	return ps
}

func (ps *CreateStudentServiceStmt) Run(
	params CreateStudentServiceParams,
) (
	err error,
) {
	querySQL := ps.querySQL

	var stmt *sqlite.Stmt
	if ps.hasSlices {
		stmt = ps.conn.Prep(querySQL)
	} else {
		stmt = ps.stmt
	}

	defer func() {
		_ = stmt.ClearBindings()
		_ = stmt.Reset()
	}()

	bindIndex := 1
	// Bind parameters
	stmt.BindText(bindIndex, params.Id)

	bindIndex++
	stmt.BindText(bindIndex, params.StudentId)

	bindIndex++
	stmt.BindText(bindIndex, params.ServiceType)

	bindIndex++
	if params.IndirectMinutes == nil {
		stmt.BindNull(bindIndex)
	} else {
		stmt.BindInt64(bindIndex, *params.IndirectMinutes)

	}
	bindIndex++
	if params.DirectMinutes == nil {
		stmt.BindNull(bindIndex)
	} else {
		stmt.BindInt64(bindIndex, *params.DirectMinutes)

	}
	bindIndex++
	if params.FrequencyCount == nil {
		stmt.BindNull(bindIndex)
	} else {
		stmt.BindInt64(bindIndex, *params.FrequencyCount)

	}
	bindIndex++
	if params.FrequencyType == nil {
		stmt.BindNull(bindIndex)
	} else {
		stmt.BindText(bindIndex, *params.FrequencyType)

	}
	bindIndex++
	if params.Location == nil {
		stmt.BindNull(bindIndex)
	} else {
		stmt.BindText(bindIndex, *params.Location)

	}
	bindIndex++
	if params.StartDate == nil {
		stmt.BindNull(bindIndex)
	} else {
		stmt.BindText(bindIndex, *params.StartDate)

	}
	bindIndex++
	if params.EndDate == nil {
		stmt.BindNull(bindIndex)
	} else {
		stmt.BindText(bindIndex, *params.EndDate)

	}
	bindIndex++
	if params.Provider == nil {
		stmt.BindNull(bindIndex)
	} else {
		stmt.BindText(bindIndex, *params.Provider)

	}
	bindIndex++
	stmt.BindText(bindIndex, params.CreatedAt)

	bindIndex++

	// Execute the query
	if _, err := stmt.Step(); err != nil {
		return fmt.Errorf("failed to execute createstudentservice SQL: %w", err)
	}

	return nil
}

func OnceCreateStudentService(
	tx *sqlite.Conn,
	params CreateStudentServiceParams,
) (
	err error,
) {
	ps := CreateStudentService(tx)

	return ps.Run(
		params,
	)
}
