// Code generated by "sqlc-gen-zombiezen". DO NOT EDIT.

package dbsql

import (
	"fmt"
	"zombiezen.com/go/sqlite"
)

type CreatePeriodParams struct {
	Id                       string `json:"id"`
	Title                    string `json:"title"`
	StartTime                string `json:"start_time"`
	Duration                 int64  `json:"duration"`
	Days                     int64  `json:"days"`
	CreatedAt                string `json:"created_at"`
	LastEventCommitPosition  int64  `json:"last_event_commit_position"`
	LastEventPreparePosition int64  `json:"last_event_prepare_position"`
}

type CreatePeriodStmt struct {
	conn      *sqlite.Conn
	stmt      *sqlite.Stmt
	querySQL  string
	hasSlices bool
}

func CreatePeriod(tx *sqlite.Conn) *CreatePeriodStmt {
	const querySQL = `
INSERT INTO periods (id, title, start_time, duration, days, created_at, updated_at, last_event_commit_position, last_event_prepare_position)
VALUES (?1, ?2, ?3, ?4, ?5, ?6, ?6, ?7, ?8)
ON CONFLICT (id) DO NOTHING
    `

	ps := &CreatePeriodStmt{
		conn:      tx,
		querySQL:  querySQL,
		hasSlices: false,
	}

	if !ps.hasSlices {
		ps.stmt = tx.Prep(querySQL)
	}

	return ps
}

func (ps *CreatePeriodStmt) Run(
	params CreatePeriodParams,
) (
	err error,
) {
	querySQL := ps.querySQL

	var stmt *sqlite.Stmt
	if ps.hasSlices {
		stmt = ps.conn.Prep(querySQL)
	} else {
		stmt = ps.stmt
	}

	defer func() {
		_ = stmt.ClearBindings()
		_ = stmt.Reset()
	}()

	bindIndex := 1
	// Bind parameters
	stmt.BindText(bindIndex, params.Id)

	bindIndex++
	stmt.BindText(bindIndex, params.Title)

	bindIndex++
	stmt.BindText(bindIndex, params.StartTime)

	bindIndex++
	stmt.BindInt64(bindIndex, params.Duration)

	bindIndex++
	stmt.BindInt64(bindIndex, params.Days)

	bindIndex++
	stmt.BindText(bindIndex, params.CreatedAt)

	bindIndex++
	stmt.BindInt64(bindIndex, params.LastEventCommitPosition)

	bindIndex++
	stmt.BindInt64(bindIndex, params.LastEventPreparePosition)

	bindIndex++

	// Execute the query
	if _, err := stmt.Step(); err != nil {
		return fmt.Errorf("failed to execute createperiod SQL: %w", err)
	}

	return nil
}

func OnceCreatePeriod(
	tx *sqlite.Conn,
	params CreatePeriodParams,
) (
	err error,
) {
	ps := CreatePeriod(tx)

	return ps.Run(
		params,
	)
}
