// Code generated by "sqlc-gen-zombiezen". DO NOT EDIT.

package dbsql

import (
	"fmt"
	"zombiezen.com/go/sqlite"
)

type DeletePeriodStmt struct {
	conn      *sqlite.Conn
	stmt      *sqlite.Stmt
	querySQL  string
	hasSlices bool
}

func DeletePeriod(tx *sqlite.Conn) *DeletePeriodStmt {
	const querySQL = `
DELETE FROM periods
WHERE id = ?1
    `

	ps := &DeletePeriodStmt{
		conn:      tx,
		querySQL:  querySQL,
		hasSlices: false,
	}

	if !ps.hasSlices {
		ps.stmt = tx.Prep(querySQL)
	}

	return ps
}

func (ps *DeletePeriodStmt) Run(
	id string,
) (
	err error,
) {
	querySQL := ps.querySQL

	var stmt *sqlite.Stmt
	if ps.hasSlices {
		stmt = ps.conn.Prep(querySQL)
	} else {
		stmt = ps.stmt
	}

	defer func() {
		_ = stmt.ClearBindings()
		_ = stmt.Reset()
	}()

	bindIndex := 1
	// Bind parameters
	stmt.BindText(bindIndex, id)

	bindIndex++

	// Execute the query
	if _, err := stmt.Step(); err != nil {
		return fmt.Errorf("failed to execute deleteperiod SQL: %w", err)
	}

	return nil
}

func OnceDeletePeriod(
	tx *sqlite.Conn,
	id string,
) (
	err error,
) {
	ps := DeletePeriod(tx)

	return ps.Run(
		id,
	)
}
