// Code generated by "sqlc-gen-zombiezen". DO NOT EDIT.

package dbsql

import (
	"fmt"
	"zombiezen.com/go/sqlite"
)

type GetUserProfileByUserIdRes struct {
	UserId string `json:"user_id"`
	Avatar string `json:"avatar"`
	Bio    string `json:"bio"`
}

type GetUserProfileByUserIdStmt struct {
	conn      *sqlite.Conn
	stmt      *sqlite.Stmt
	querySQL  string
	hasSlices bool
}

func GetUserProfileByUserId(tx *sqlite.Conn) *GetUserProfileByUserIdStmt {
	const querySQL = `
SELECT 
	user_id,
	coalesce(avatar, '') AS avatar,
	coalesce(bio, '') AS bio
FROM profile_stats
WHERE user_id = ?1
    `

	ps := &GetUserProfileByUserIdStmt{
		conn:      tx,
		querySQL:  querySQL,
		hasSlices: false,
	}

	if !ps.hasSlices {
		ps.stmt = tx.Prep(querySQL)
	}

	return ps
}

func (ps *GetUserProfileByUserIdStmt) Run(
	userId string,
) (
	res *GetUserProfileByUserIdRes,
	err error,
) {
	querySQL := ps.querySQL

	var stmt *sqlite.Stmt
	if ps.hasSlices {
		stmt = ps.conn.Prep(querySQL)
	} else {
		stmt = ps.stmt
	}

	defer func() {
		_ = stmt.ClearBindings()
		_ = stmt.Reset()
	}()

	bindIndex := 1
	// Bind parameters
	stmt.BindText(bindIndex, userId)

	bindIndex++

	// Execute the query
	if hasRow, err := stmt.Step(); err != nil {
		return res, fmt.Errorf("failed to execute {{.Name.Lower}} SQL: %w", err)
	} else if hasRow {
		row := GetUserProfileByUserIdRes{}
		row.UserId = stmt.ColumnText(0)
		row.Avatar = stmt.ColumnText(1)
		row.Bio = stmt.ColumnText(2)
		res = &row
	}

	return res, nil
}

func OnceGetUserProfileByUserId(
	tx *sqlite.Conn,
	userId string,
) (
	res *GetUserProfileByUserIdRes,
	err error,
) {
	ps := GetUserProfileByUserId(tx)

	return ps.Run(
		userId,
	)
}
