// Code generated by "sqlc-gen-zombiezen". DO NOT EDIT.

package dbsql

import (
	"fmt"
	"zombiezen.com/go/sqlite"
)

type GetScheduleRes struct {
	Id        string `json:"id"`
	Title     string `json:"title"`
	TeacherId string `json:"teacher_id"`
}

type GetScheduleStmt struct {
	conn      *sqlite.Conn
	stmt      *sqlite.Stmt
	querySQL  string
	hasSlices bool
}

func GetSchedule(tx *sqlite.Conn) *GetScheduleStmt {
	const querySQL = `
SELECT id, title, teacher_id
FROM schedules
WHERE deleted_at IS NULL
	AND id = ?1
    `

	ps := &GetScheduleStmt{
		conn:      tx,
		querySQL:  querySQL,
		hasSlices: false,
	}

	if !ps.hasSlices {
		ps.stmt = tx.Prep(querySQL)
	}

	return ps
}

func (ps *GetScheduleStmt) Run(
	id string,
) (
	res *GetScheduleRes,
	err error,
) {
	querySQL := ps.querySQL

	var stmt *sqlite.Stmt
	if ps.hasSlices {
		stmt = ps.conn.Prep(querySQL)
	} else {
		stmt = ps.stmt
	}

	defer func() {
		_ = stmt.ClearBindings()
		_ = stmt.Reset()
	}()

	bindIndex := 1
	// Bind parameters
	stmt.BindText(bindIndex, id)

	bindIndex++

	// Execute the query
	if hasRow, err := stmt.Step(); err != nil {
		return res, fmt.Errorf("failed to execute {{.Name.Lower}} SQL: %w", err)
	} else if hasRow {
		row := GetScheduleRes{}
		row.Id = stmt.ColumnText(0)
		row.Title = stmt.ColumnText(1)
		row.TeacherId = stmt.ColumnText(2)
		res = &row
	}

	return res, nil
}

func OnceGetSchedule(
	tx *sqlite.Conn,
	id string,
) (
	res *GetScheduleRes,
	err error,
) {
	ps := GetSchedule(tx)

	return ps.Run(
		id,
	)
}
