// Code generated by "sqlc-gen-zombiezen". DO NOT EDIT.

package dbsql

import (
	"fmt"
	"zombiezen.com/go/sqlite"
)

type GetEducatorRes struct {
	Id         string `json:"id"`
	GivenName  string `json:"given_name"`
	ChosenName string `json:"chosen_name"`
	FamilyName string `json:"family_name"`
	Role       string `json:"role"`
	Email      string `json:"email"`
	CreatedAt  string `json:"created_at"`
	UpdatedAt  string `json:"updated_at"`
}

type GetEducatorStmt struct {
	conn      *sqlite.Conn
	stmt      *sqlite.Stmt
	querySQL  string
	hasSlices bool
}

func GetEducator(tx *sqlite.Conn) *GetEducatorStmt {
	const querySQL = `
SELECT 
	id, 
	given_name, 
	chosen_name, 
	family_name, 
	role,
	email, 
	created_at, 
	updated_at
FROM educators
WHERE archived_at IS NULL
	AND id = ?1
    `

	ps := &GetEducatorStmt{
		conn:      tx,
		querySQL:  querySQL,
		hasSlices: false,
	}

	if !ps.hasSlices {
		ps.stmt = tx.Prep(querySQL)
	}

	return ps
}

func (ps *GetEducatorStmt) Run(
	id string,
) (
	res *GetEducatorRes,
	err error,
) {
	querySQL := ps.querySQL

	var stmt *sqlite.Stmt
	if ps.hasSlices {
		stmt = ps.conn.Prep(querySQL)
	} else {
		stmt = ps.stmt
	}

	defer func() {
		_ = stmt.ClearBindings()
		_ = stmt.Reset()
	}()

	bindIndex := 1
	// Bind parameters
	stmt.BindText(bindIndex, id)

	bindIndex++

	// Execute the query
	if hasRow, err := stmt.Step(); err != nil {
		return res, fmt.Errorf("failed to execute {{.Name.Lower}} SQL: %w", err)
	} else if hasRow {
		row := GetEducatorRes{}
		row.Id = stmt.ColumnText(0)
		row.GivenName = stmt.ColumnText(1)
		row.ChosenName = stmt.ColumnText(2)
		row.FamilyName = stmt.ColumnText(3)
		row.Role = stmt.ColumnText(4)
		row.Email = stmt.ColumnText(5)
		row.CreatedAt = stmt.ColumnText(6)
		row.UpdatedAt = stmt.ColumnText(7)
		res = &row
	}

	return res, nil
}

func OnceGetEducator(
	tx *sqlite.Conn,
	id string,
) (
	res *GetEducatorRes,
	err error,
) {
	ps := GetEducator(tx)

	return ps.Run(
		id,
	)
}
