// Code generated by "sqlc-gen-zombiezen". DO NOT EDIT.

package dbsql

import (
	"fmt"
	"zombiezen.com/go/sqlite"
)

type InsertCreatedStudentParams struct {
	Id                       string  `json:"id"`
	FirstName                string  `json:"first_name"`
	ChosenName               *string `json:"chosen_name"`
	LastName                 string  `json:"last_name"`
	Grade                    int64   `json:"grade"`
	Homeroom                 string  `json:"homeroom"`
	CaseManager              *string `json:"case_manager"`
	LastEventCommitPosition  int64   `json:"last_event_commit_position"`
	LastEventPreparePosition int64   `json:"last_event_prepare_position"`
	CreatedAt                string  `json:"created_at"`
}

type InsertCreatedStudentStmt struct {
	conn      *sqlite.Conn
	stmt      *sqlite.Stmt
	querySQL  string
	hasSlices bool
}

func InsertCreatedStudent(tx *sqlite.Conn) *InsertCreatedStudentStmt {
	const querySQL = `
INSERT INTO students (id, first_name, chosen_name, last_name, grade, homeroom, case_manager, deleted_at, last_event_commit_position, last_event_prepare_position, created_at, updated_at)
VALUES (?1, ?2, ?3, ?4, ?5, ?6, ?7, null, ?8, ?9, ?10, ?10)
ON CONFLICT (id) DO NOTHING
    `

	ps := &InsertCreatedStudentStmt{
		conn:      tx,
		querySQL:  querySQL,
		hasSlices: false,
	}

	if !ps.hasSlices {
		ps.stmt = tx.Prep(querySQL)
	}

	return ps
}

func (ps *InsertCreatedStudentStmt) Run(
	params InsertCreatedStudentParams,
) (
	err error,
) {
	querySQL := ps.querySQL

	var stmt *sqlite.Stmt
	if ps.hasSlices {
		stmt = ps.conn.Prep(querySQL)
	} else {
		stmt = ps.stmt
	}

	defer func() {
		_ = stmt.ClearBindings()
		_ = stmt.Reset()
	}()

	bindIndex := 1
	// Bind parameters
	stmt.BindText(bindIndex, params.Id)

	bindIndex++
	stmt.BindText(bindIndex, params.FirstName)

	bindIndex++
	if params.ChosenName == nil {
		stmt.BindNull(bindIndex)
	} else {
		stmt.BindText(bindIndex, *params.ChosenName)

	}
	bindIndex++
	stmt.BindText(bindIndex, params.LastName)

	bindIndex++
	stmt.BindInt64(bindIndex, params.Grade)

	bindIndex++
	stmt.BindText(bindIndex, params.Homeroom)

	bindIndex++
	if params.CaseManager == nil {
		stmt.BindNull(bindIndex)
	} else {
		stmt.BindText(bindIndex, *params.CaseManager)

	}
	bindIndex++
	stmt.BindInt64(bindIndex, params.LastEventCommitPosition)

	bindIndex++
	stmt.BindInt64(bindIndex, params.LastEventPreparePosition)

	bindIndex++
	stmt.BindText(bindIndex, params.CreatedAt)

	bindIndex++

	// Execute the query
	if _, err := stmt.Step(); err != nil {
		return fmt.Errorf("failed to execute insertcreatedstudent SQL: %w", err)
	}

	return nil
}

func OnceInsertCreatedStudent(
	tx *sqlite.Conn,
	params InsertCreatedStudentParams,
) (
	err error,
) {
	ps := InsertCreatedStudent(tx)

	return ps.Run(
		params,
	)
}
