// Code generated by "sqlc-gen-zombiezen". DO NOT EDIT.

package dbsql

import (
	"fmt"
	"zombiezen.com/go/sqlite"
)

type ListOnlyStudentsWithIepsRes struct {
	StudentId    string `json:"student_id"`
	MarssId      string `json:"marss_id"`
	Birthdate    string `json:"birthdate"`
	GivenName    string `json:"given_name"`
	ChosenName   string `json:"chosen_name"`
	FamilyName   string `json:"family_name"`
	Pronouns     string `json:"pronouns"`
	Email        string `json:"email"`
	Username     string `json:"username"`
	Grade        int64  `json:"grade"`
	HomeroomId   string `json:"homeroom_id"`
	PlanType     int64  `json:"plan_type"`
	CreatedAt    string `json:"created_at"`
	UpdatedAt    string `json:"updated_at"`
	IepId        string `json:"iep_id"`
	StartDate    string `json:"start_date"`
	EndDate      string `json:"end_date"`
	AmendedDate  string `json:"amended_date"`
	IepCreatedAt string `json:"iep_created_at"`
	IepUpdatedAt string `json:"iep_updated_at"`
}

type ListOnlyStudentsWithIepsStmt struct {
	conn      *sqlite.Conn
	stmt      *sqlite.Stmt
	querySQL  string
	hasSlices bool
}

func ListOnlyStudentsWithIeps(tx *sqlite.Conn) *ListOnlyStudentsWithIepsStmt {
	const querySQL = `
SELECT
	s.id AS student_id,
	s.marss_id,
	s.birthdate,
	s.given_name,
	s.chosen_name,
	s.family_name,
	s.pronouns,
	s.email,
	s.username,
	s.grade,
	s.homeroom_id, 
	s.plan_type, 
	s.created_at,
	s.updated_at,
	i.id AS iep_id,
	i.start_date,
	i.end_date,
	i.amended_date,
	i.created_at AS iep_created_at,
	i.updated_at AS iep_updated_at
FROM students s
INNER JOIN student_ieps i ON s.id = i.student_id
WHERE s.archived_at IS NULL
  AND i.archived_at IS NULL
ORDER BY s.family_name COLLATE NOCASE ASC, s.chosen_name COLLATE NOCASE ASC, s.given_name COLLATE NOCASE ASC
    `

	ps := &ListOnlyStudentsWithIepsStmt{
		conn:      tx,
		querySQL:  querySQL,
		hasSlices: false,
	}

	if !ps.hasSlices {
		ps.stmt = tx.Prep(querySQL)
	}

	return ps
}

func (ps *ListOnlyStudentsWithIepsStmt) Run() (
	res []ListOnlyStudentsWithIepsRes,
	err error,
) {
	querySQL := ps.querySQL

	var stmt *sqlite.Stmt
	if ps.hasSlices {
		stmt = ps.conn.Prep(querySQL)
	} else {
		stmt = ps.stmt
	}

	defer func() {
		_ = stmt.ClearBindings()
		_ = stmt.Reset()
	}()

	// Execute the query
	for {
		if hasRow, err := stmt.Step(); err != nil {
			return res, fmt.Errorf("failed to execute {{.Name.Lower}} SQL: %w", err)
		} else if !hasRow {
			break
		}

		row := ListOnlyStudentsWithIepsRes{}
		row.StudentId = stmt.ColumnText(0)
		row.MarssId = stmt.ColumnText(1)
		row.Birthdate = stmt.ColumnText(2)
		row.GivenName = stmt.ColumnText(3)
		row.ChosenName = stmt.ColumnText(4)
		row.FamilyName = stmt.ColumnText(5)
		row.Pronouns = stmt.ColumnText(6)
		row.Email = stmt.ColumnText(7)
		row.Username = stmt.ColumnText(8)
		row.Grade = stmt.ColumnInt64(9)
		row.HomeroomId = stmt.ColumnText(10)
		row.PlanType = stmt.ColumnInt64(11)
		row.CreatedAt = stmt.ColumnText(12)
		row.UpdatedAt = stmt.ColumnText(13)
		row.IepId = stmt.ColumnText(14)
		row.StartDate = stmt.ColumnText(15)
		row.EndDate = stmt.ColumnText(16)
		row.AmendedDate = stmt.ColumnText(17)
		row.IepCreatedAt = stmt.ColumnText(18)
		row.IepUpdatedAt = stmt.ColumnText(19)
		res = append(res, row)
	}

	return res, nil
}

func OnceListOnlyStudentsWithIeps(
	tx *sqlite.Conn,
) (
	res []ListOnlyStudentsWithIepsRes,
	err error,
) {
	ps := ListOnlyStudentsWithIeps(tx)

	return ps.Run()
}
