// Code generated by "sqlc-gen-zombiezen". DO NOT EDIT.

package dbsql

import (
	"fmt"
	"zombiezen.com/go/sqlite"
)

type ListStudentsRes struct {
	ID				string `json:"id"`
	FirstName	string `json:"first_name"`
	CreatedAt string `json:"created_at"`
	UpdatedAt string `json:"updated_at"`
}

type ListStudentsStmt struct {
	conn      *sqlite.Conn
	stmt      *sqlite.Stmt
	querySQL  string
	hasSlices bool
}

func ListStudents(tx *sqlite.Conn) *ListStudentsStmt {
	const querySQL = `
SELECT id, first_name, grade, created_at, updated_at
FROM students
WHERE deleted_at IS NULL
ORDER BY created_at DESC, todo_id DESC
    `

	ps := &ListStudentsStmt{
		conn:      tx,
		querySQL:  querySQL,
		hasSlices: false,
	}

	if !ps.hasSlices {
		ps.stmt = tx.Prep(querySQL)
	}

	return ps
}

func (ps *ListStudentsStmt) Run(
	userRegisteredId string,
) (
	res []ListStudentsRes,
	err error,
) {
	querySQL := ps.querySQL

	var stmt *sqlite.Stmt
	if ps.hasSlices {
		stmt = ps.conn.Prep(querySQL)
	} else {
		stmt = ps.stmt
	}

	defer func() {
		_ = stmt.ClearBindings()
		_ = stmt.Reset()
	}()

	bindIndex := 1
	// Bind parameters
	stmt.BindText(bindIndex, userRegisteredId)

	bindIndex++

	// Execute the query
	for {
		if hasRow, err := stmt.Step(); err != nil {
			return res, fmt.Errorf("failed to execute {{.Name.Lower}} SQL: %w", err)
		} else if !hasRow {
			break
		}

		row := ListStudentsRes{}
		row.ID = stmt.ColumnText(0)
		row.FirstName = stmt.ColumnText(1)
		row.CreatedAt = stmt.ColumnText(8)
		row.UpdatedAt = stmt.ColumnText(9)
		res = append(res, row)
	}

	return res, nil
}

func OnceListStudents(
	tx *sqlite.Conn,
	userRegisteredId string,
) (
	res []ListStudentsRes,
	err error,
) {
	ps := ListStudents(tx)

	return ps.Run(
		userRegisteredId,
	)
}
