// Code generated by "sqlc-gen-zombiezen". DO NOT EDIT.

package dbsql

import (
	"fmt"
	"zombiezen.com/go/sqlite"
)

type ListHomeroomsRes struct {
	Id         string `json:"id"`
	Title      string `json:"title"`
	LocationId string `json:"location_id"`
	CreatedAt  string `json:"created_at"`
	UpdatedAt  string `json:"updated_at"`
}

type ListHomeroomsStmt struct {
	conn      *sqlite.Conn
	stmt      *sqlite.Stmt
	querySQL  string
	hasSlices bool
}

func ListHomerooms(tx *sqlite.Conn) *ListHomeroomsStmt {
	const querySQL = `
SELECT
	id, 
	title, 
	location_id,
	created_at, 
	updated_at
FROM homerooms
WHERE archived_at IS NULL
ORDER BY title ASC
    `

	ps := &ListHomeroomsStmt{
		conn:      tx,
		querySQL:  querySQL,
		hasSlices: false,
	}

	if !ps.hasSlices {
		ps.stmt = tx.Prep(querySQL)
	}

	return ps
}

func (ps *ListHomeroomsStmt) Run() (
	res []ListHomeroomsRes,
	err error,
) {
	querySQL := ps.querySQL

	var stmt *sqlite.Stmt
	if ps.hasSlices {
		stmt = ps.conn.Prep(querySQL)
	} else {
		stmt = ps.stmt
	}

	defer func() {
		_ = stmt.ClearBindings()
		_ = stmt.Reset()
	}()

	// Execute the query
	for {
		if hasRow, err := stmt.Step(); err != nil {
			return res, fmt.Errorf("failed to execute {{.Name.Lower}} SQL: %w", err)
		} else if !hasRow {
			break
		}

		row := ListHomeroomsRes{}
		row.Id = stmt.ColumnText(0)
		row.Title = stmt.ColumnText(1)
		row.LocationId = stmt.ColumnText(2)
		row.CreatedAt = stmt.ColumnText(3)
		row.UpdatedAt = stmt.ColumnText(4)
		res = append(res, row)
	}

	return res, nil
}

func OnceListHomerooms(
	tx *sqlite.Conn,
) (
	res []ListHomeroomsRes,
	err error,
) {
	ps := ListHomerooms(tx)

	return ps.Run()
}
