// Code generated by "sqlc-gen-zombiezen". DO NOT EDIT.

package dbsql

import (
	"fmt"
	"zombiezen.com/go/sqlite"
)

type ListPeriodsForScheduleRes struct {
	Id         string `json:"id"`
	ScheduleId string `json:"schedule_id"`
	PeriodId   string `json:"period_id"`
}

type ListPeriodsForScheduleStmt struct {
	conn      *sqlite.Conn
	stmt      *sqlite.Stmt
	querySQL  string
	hasSlices bool
}

func ListPeriodsForSchedule(tx *sqlite.Conn) *ListPeriodsForScheduleStmt {
	const querySQL = `
SELECT id, schedule_id, period_id
FROM schedule_periods
WHERE schedule_id = ?1 AND
	deleted_at IS NULL
ORDER BY id DESC
    `

	ps := &ListPeriodsForScheduleStmt{
		conn:      tx,
		querySQL:  querySQL,
		hasSlices: false,
	}

	if !ps.hasSlices {
		ps.stmt = tx.Prep(querySQL)
	}

	return ps
}

func (ps *ListPeriodsForScheduleStmt) Run(
	scheduleId string,
) (
	res []ListPeriodsForScheduleRes,
	err error,
) {
	querySQL := ps.querySQL

	var stmt *sqlite.Stmt
	if ps.hasSlices {
		stmt = ps.conn.Prep(querySQL)
	} else {
		stmt = ps.stmt
	}

	defer func() {
		_ = stmt.ClearBindings()
		_ = stmt.Reset()
	}()

	bindIndex := 1
	// Bind parameters
	stmt.BindText(bindIndex, scheduleId)

	bindIndex++

	// Execute the query
	for {
		if hasRow, err := stmt.Step(); err != nil {
			return res, fmt.Errorf("failed to execute {{.Name.Lower}} SQL: %w", err)
		} else if !hasRow {
			break
		}

		row := ListPeriodsForScheduleRes{}
		row.Id = stmt.ColumnText(0)
		row.ScheduleId = stmt.ColumnText(1)
		row.PeriodId = stmt.ColumnText(2)
		res = append(res, row)
	}

	return res, nil
}

func OnceListPeriodsForSchedule(
	tx *sqlite.Conn,
	scheduleId string,
) (
	res []ListPeriodsForScheduleRes,
	err error,
) {
	ps := ListPeriodsForSchedule(tx)

	return ps.Run(
		scheduleId,
	)
}
