// Code generated by "sqlc-gen-zombiezen". DO NOT EDIT.

package dbsql

import (
	"fmt"
	"zombiezen.com/go/sqlite"
)

type ListStudentsForPeriodRes struct {
	Id         string `json:"id"`
	MarssId    string `json:"marss_id"`
	Birthdate  string `json:"birthdate"`
	GivenName  string `json:"given_name"`
	ChosenName string `json:"chosen_name"`
	FamilyName string `json:"family_name"`
	Pronouns   string `json:"pronouns"`
	Email      string `json:"email"`
	Username   string `json:"username"`
	Grade      int64  `json:"grade"`
	HomeroomId string `json:"homeroom_id"`
	PlanType   int64  `json:"plan_type"`
	CreatedAt  string `json:"created_at"`
	UpdatedAt  string `json:"updated_at"`
}

type ListStudentsForPeriodStmt struct {
	conn      *sqlite.Conn
	stmt      *sqlite.Stmt
	querySQL  string
	hasSlices bool
}

func ListStudentsForPeriod(tx *sqlite.Conn) *ListStudentsForPeriodStmt {
	const querySQL = `
SELECT
	s.id, 
	s.marss_id,
	s.birthdate,
	s.given_name, 
	s.chosen_name, 
	s.family_name, 
	s.pronouns,
	s.email,
	s.username,
	s.grade, 
	s.homeroom_id, 
	s.plan_type, 
	s.created_at,
	s.updated_at
FROM students s
JOIN periods_students ps ON s.id = ps.student_id
WHERE ps.period_id = ?1
ORDER BY family_name COLLATE NOCASE ASC, given_name COLLATE NOCASE ASC
    `

	ps := &ListStudentsForPeriodStmt{
		conn:      tx,
		querySQL:  querySQL,
		hasSlices: false,
	}

	if !ps.hasSlices {
		ps.stmt = tx.Prep(querySQL)
	}

	return ps
}

func (ps *ListStudentsForPeriodStmt) Run(
	periodId string,
) (
	res []ListStudentsForPeriodRes,
	err error,
) {
	querySQL := ps.querySQL

	var stmt *sqlite.Stmt
	if ps.hasSlices {
		stmt = ps.conn.Prep(querySQL)
	} else {
		stmt = ps.stmt
	}

	defer func() {
		_ = stmt.ClearBindings()
		_ = stmt.Reset()
	}()

	bindIndex := 1
	// Bind parameters
	stmt.BindText(bindIndex, periodId)

	bindIndex++

	// Execute the query
	for {
		if hasRow, err := stmt.Step(); err != nil {
			return res, fmt.Errorf("failed to execute {{.Name.Lower}} SQL: %w", err)
		} else if !hasRow {
			break
		}

		row := ListStudentsForPeriodRes{}
		row.Id = stmt.ColumnText(0)
		row.MarssId = stmt.ColumnText(1)
		row.Birthdate = stmt.ColumnText(2)
		row.GivenName = stmt.ColumnText(3)
		row.ChosenName = stmt.ColumnText(4)
		row.FamilyName = stmt.ColumnText(5)
		row.Pronouns = stmt.ColumnText(6)
		row.Email = stmt.ColumnText(7)
		row.Username = stmt.ColumnText(8)
		row.Grade = stmt.ColumnInt64(9)
		row.HomeroomId = stmt.ColumnText(10)
		row.PlanType = stmt.ColumnInt64(11)
		row.CreatedAt = stmt.ColumnText(12)
		row.UpdatedAt = stmt.ColumnText(13)
		res = append(res, row)
	}

	return res, nil
}

func OnceListStudentsForPeriod(
	tx *sqlite.Conn,
	periodId string,
) (
	res []ListStudentsForPeriodRes,
	err error,
) {
	ps := ListStudentsForPeriod(tx)

	return ps.Run(
		periodId,
	)
}
