// Code generated by "sqlc-gen-zombiezen". DO NOT EDIT.

package dbsql

import (
	"fmt"
	"zombiezen.com/go/sqlite"
)

type RemovePeriodFromScheduleParams struct {
	ScheduleId string `json:"schedule_id"`
	PeriodId   string `json:"period_id"`
}

type RemovePeriodFromScheduleStmt struct {
	conn      *sqlite.Conn
	stmt      *sqlite.Stmt
	querySQL  string
	hasSlices bool
}

func RemovePeriodFromSchedule(tx *sqlite.Conn) *RemovePeriodFromScheduleStmt {
	const querySQL = `
DELETE FROM schedule_periods
WHERE schedule_id = ?1 AND period_id = ?2
    `

	ps := &RemovePeriodFromScheduleStmt{
		conn:      tx,
		querySQL:  querySQL,
		hasSlices: false,
	}

	if !ps.hasSlices {
		ps.stmt = tx.Prep(querySQL)
	}

	return ps
}

func (ps *RemovePeriodFromScheduleStmt) Run(
	params RemovePeriodFromScheduleParams,
) (
	err error,
) {
	querySQL := ps.querySQL

	var stmt *sqlite.Stmt
	if ps.hasSlices {
		stmt = ps.conn.Prep(querySQL)
	} else {
		stmt = ps.stmt
	}

	defer func() {
		_ = stmt.ClearBindings()
		_ = stmt.Reset()
	}()

	bindIndex := 1
	// Bind parameters
	stmt.BindText(bindIndex, params.ScheduleId)

	bindIndex++
	stmt.BindText(bindIndex, params.PeriodId)

	bindIndex++

	// Execute the query
	if _, err := stmt.Step(); err != nil {
		return fmt.Errorf("failed to execute removeperiodfromschedule SQL: %w", err)
	}

	return nil
}

func OnceRemovePeriodFromSchedule(
	tx *sqlite.Conn,
	params RemovePeriodFromScheduleParams,
) (
	err error,
) {
	ps := RemovePeriodFromSchedule(tx)

	return ps.Run(
		params,
	)
}
