// Code generated by "sqlc-gen-zombiezen". DO NOT EDIT.

package dbsql

import (
	"fmt"
	"zombiezen.com/go/sqlite"
)

type RemoveEducatorFromHomeroomParams struct {
	HomeroomId string `json:"homeroom_id"`
	EducatorId string `json:"educator_id"`
}

type RemoveEducatorFromHomeroomStmt struct {
	conn      *sqlite.Conn
	stmt      *sqlite.Stmt
	querySQL  string
	hasSlices bool
}

func RemoveEducatorFromHomeroom(tx *sqlite.Conn) *RemoveEducatorFromHomeroomStmt {
	const querySQL = `
DELETE FROM homerooms_educators
WHERE homeroom_id = ?1 
	AND educator_id = ?2
    `

	ps := &RemoveEducatorFromHomeroomStmt{
		conn:      tx,
		querySQL:  querySQL,
		hasSlices: false,
	}

	if !ps.hasSlices {
		ps.stmt = tx.Prep(querySQL)
	}

	return ps
}

func (ps *RemoveEducatorFromHomeroomStmt) Run(
	params RemoveEducatorFromHomeroomParams,
) (
	err error,
) {
	querySQL := ps.querySQL

	var stmt *sqlite.Stmt
	if ps.hasSlices {
		stmt = ps.conn.Prep(querySQL)
	} else {
		stmt = ps.stmt
	}

	defer func() {
		_ = stmt.ClearBindings()
		_ = stmt.Reset()
	}()

	bindIndex := 1
	// Bind parameters
	stmt.BindText(bindIndex, params.HomeroomId)

	bindIndex++
	stmt.BindText(bindIndex, params.EducatorId)

	bindIndex++

	// Execute the query
	if _, err := stmt.Step(); err != nil {
		return fmt.Errorf("failed to execute removeeducatorfromhomeroom SQL: %w", err)
	}

	return nil
}

func OnceRemoveEducatorFromHomeroom(
	tx *sqlite.Conn,
	params RemoveEducatorFromHomeroomParams,
) (
	err error,
) {
	ps := RemoveEducatorFromHomeroom(tx)

	return ps.Run(
		params,
	)
}
