// Code generated by "sqlc-gen-zombiezen". DO NOT EDIT.

package dbsql

import (
	"fmt"
	"zombiezen.com/go/sqlite"
)

type RenameStudentParams struct {
	FirstName                string  `json:"first_name"`
	ChosenName               *string `json:"chosen_name"`
	LastName                 string  `json:"last_name"`
	LastEventCommitPosition  int64   `json:"last_event_commit_position"`
	LastEventPreparePosition int64   `json:"last_event_prepare_position"`
	UpdatedAt                string  `json:"updated_at"`
	Id                       string  `json:"id"`
}

type RenameStudentStmt struct {
	conn      *sqlite.Conn
	stmt      *sqlite.Stmt
	querySQL  string
	hasSlices bool
}

func RenameStudent(tx *sqlite.Conn) *RenameStudentStmt {
	const querySQL = `
UPDATE students
SET first_name = ?1,
	chosen_name = ?2,
	last_name = ?3,
	last_event_commit_position = ?4,
	last_event_prepare_position = ?5,
	updated_at = ?6
WHERE id = ?7
    `

	ps := &RenameStudentStmt{
		conn:      tx,
		querySQL:  querySQL,
		hasSlices: false,
	}

	if !ps.hasSlices {
		ps.stmt = tx.Prep(querySQL)
	}

	return ps
}

func (ps *RenameStudentStmt) Run(
	params RenameStudentParams,
) (
	err error,
) {
	querySQL := ps.querySQL

	var stmt *sqlite.Stmt
	if ps.hasSlices {
		stmt = ps.conn.Prep(querySQL)
	} else {
		stmt = ps.stmt
	}

	defer func() {
		_ = stmt.ClearBindings()
		_ = stmt.Reset()
	}()

	bindIndex := 1
	// Bind parameters
	stmt.BindText(bindIndex, params.FirstName)

	bindIndex++
	if params.ChosenName == nil {
		stmt.BindNull(bindIndex)
	} else {
		stmt.BindText(bindIndex, *params.ChosenName)

	}
	bindIndex++
	stmt.BindText(bindIndex, params.LastName)

	bindIndex++
	stmt.BindInt64(bindIndex, params.LastEventCommitPosition)

	bindIndex++
	stmt.BindInt64(bindIndex, params.LastEventPreparePosition)

	bindIndex++
	stmt.BindText(bindIndex, params.UpdatedAt)

	bindIndex++
	stmt.BindText(bindIndex, params.Id)

	bindIndex++

	// Execute the query
	if _, err := stmt.Step(); err != nil {
		return fmt.Errorf("failed to execute renamestudent SQL: %w", err)
	}

	return nil
}

func OnceRenameStudent(
	tx *sqlite.Conn,
	params RenameStudentParams,
) (
	err error,
) {
	ps := RenameStudent(tx)

	return ps.Run(
		params,
	)
}
