// Code generated by "sqlc-gen-zombiezen". DO NOT EDIT.

package dbsql

import (
	"fmt"
	"zombiezen.com/go/sqlite"
)

type ResetReadModelPeriodsStudentsStmt struct {
	conn      *sqlite.Conn
	stmt      *sqlite.Stmt
	querySQL  string
	hasSlices bool
}

func ResetReadModelPeriodsStudents(tx *sqlite.Conn) *ResetReadModelPeriodsStudentsStmt {
	const querySQL = `
DELETE FROM periods_students
    `

	ps := &ResetReadModelPeriodsStudentsStmt{
		conn:      tx,
		querySQL:  querySQL,
		hasSlices: false,
	}

	if !ps.hasSlices {
		ps.stmt = tx.Prep(querySQL)
	}

	return ps
}

func (ps *ResetReadModelPeriodsStudentsStmt) Run() (
	err error,
) {
	querySQL := ps.querySQL

	var stmt *sqlite.Stmt
	if ps.hasSlices {
		stmt = ps.conn.Prep(querySQL)
	} else {
		stmt = ps.stmt
	}

	defer func() {
		_ = stmt.ClearBindings()
		_ = stmt.Reset()
	}()

	// Execute the query
	if _, err := stmt.Step(); err != nil {
		return fmt.Errorf("failed to execute resetreadmodelperiodsstudents SQL: %w", err)
	}

	return nil
}

func OnceResetReadModelPeriodsStudents(
	tx *sqlite.Conn,
) (
	err error,
) {
	ps := ResetReadModelPeriodsStudents(tx)

	return ps.Run()
}
