// Code generated by "sqlc-gen-zombiezen". DO NOT EDIT.

package dbsql

import (
	"fmt"
	"zombiezen.com/go/sqlite"
)

type UpdateStudentServiceParams struct {
	StudentId       string  `json:"student_id"`
	ServiceType     string  `json:"service_type"`
	IndirectMinutes *int64  `json:"indirect_minutes"`
	DirectMinutes   *int64  `json:"direct_minutes"`
	FrequencyCount  *int64  `json:"frequency_count"`
	FrequencyType   *string `json:"frequency_type"`
	Location        *string `json:"location"`
	StartDate       *string `json:"start_date"`
	EndDate         *string `json:"end_date"`
	Provider        *string `json:"provider"`
	UpdatedAt       string  `json:"updated_at"`
	Id              string  `json:"id"`
}

type UpdateStudentServiceStmt struct {
	conn      *sqlite.Conn
	stmt      *sqlite.Stmt
	querySQL  string
	hasSlices bool
}

func UpdateStudentService(tx *sqlite.Conn) *UpdateStudentServiceStmt {
	const querySQL = `
UPDATE student_services
SET
	student_id = ?1,
	service_type = ?2,
	indirect_minutes = ?3,
	direct_minutes = ?4,
	frequency_count = ?5,
	frequency_type = ?6,
	location = ?7,
	start_date = ?8,
	end_date = ?9,
	provider = ?10,
	updated_at = ?11
WHERE id = ?12
    `

	ps := &UpdateStudentServiceStmt{
		conn:      tx,
		querySQL:  querySQL,
		hasSlices: false,
	}

	if !ps.hasSlices {
		ps.stmt = tx.Prep(querySQL)
	}

	return ps
}

func (ps *UpdateStudentServiceStmt) Run(
	params UpdateStudentServiceParams,
) (
	err error,
) {
	querySQL := ps.querySQL

	var stmt *sqlite.Stmt
	if ps.hasSlices {
		stmt = ps.conn.Prep(querySQL)
	} else {
		stmt = ps.stmt
	}

	defer func() {
		_ = stmt.ClearBindings()
		_ = stmt.Reset()
	}()

	bindIndex := 1
	// Bind parameters
	stmt.BindText(bindIndex, params.StudentId)

	bindIndex++
	stmt.BindText(bindIndex, params.ServiceType)

	bindIndex++
	if params.IndirectMinutes == nil {
		stmt.BindNull(bindIndex)
	} else {
		stmt.BindInt64(bindIndex, *params.IndirectMinutes)

	}
	bindIndex++
	if params.DirectMinutes == nil {
		stmt.BindNull(bindIndex)
	} else {
		stmt.BindInt64(bindIndex, *params.DirectMinutes)

	}
	bindIndex++
	if params.FrequencyCount == nil {
		stmt.BindNull(bindIndex)
	} else {
		stmt.BindInt64(bindIndex, *params.FrequencyCount)

	}
	bindIndex++
	if params.FrequencyType == nil {
		stmt.BindNull(bindIndex)
	} else {
		stmt.BindText(bindIndex, *params.FrequencyType)

	}
	bindIndex++
	if params.Location == nil {
		stmt.BindNull(bindIndex)
	} else {
		stmt.BindText(bindIndex, *params.Location)

	}
	bindIndex++
	if params.StartDate == nil {
		stmt.BindNull(bindIndex)
	} else {
		stmt.BindText(bindIndex, *params.StartDate)

	}
	bindIndex++
	if params.EndDate == nil {
		stmt.BindNull(bindIndex)
	} else {
		stmt.BindText(bindIndex, *params.EndDate)

	}
	bindIndex++
	if params.Provider == nil {
		stmt.BindNull(bindIndex)
	} else {
		stmt.BindText(bindIndex, *params.Provider)

	}
	bindIndex++
	stmt.BindText(bindIndex, params.UpdatedAt)

	bindIndex++
	stmt.BindText(bindIndex, params.Id)

	bindIndex++

	// Execute the query
	if _, err := stmt.Step(); err != nil {
		return fmt.Errorf("failed to execute updatestudentservice SQL: %w", err)
	}

	return nil
}

func OnceUpdateStudentService(
	tx *sqlite.Conn,
	params UpdateStudentServiceParams,
) (
	err error,
) {
	ps := UpdateStudentService(tx)

	return ps.Run(
		params,
	)
}
