// Code generated by "sqlc-gen-zombiezen". DO NOT EDIT.

package dbsql

import (
	"fmt"
	"zombiezen.com/go/sqlite"
)

type UserByIdorRegisteredIdRes struct {
	Id               string `json:"id"`
	UserRegisteredId string `json:"user_registered_id"`
	Email            string `json:"email"`
	Username         string `json:"username"`
	Avatar           string `json:"avatar"`
	Bio              string `json:"bio"`
}

type UserByIdorRegisteredIdStmt struct {
	conn      *sqlite.Conn
	stmt      *sqlite.Stmt
	querySQL  string
	hasSlices bool
}

func UserByIdorRegisteredId(tx *sqlite.Conn) *UserByIdorRegisteredIdStmt {
	const querySQL = `
SELECT 
	u.id,
	u.user_registered_id,
	u.email,
	u.username,
	coalesce(u.avatar, '') AS avatar,
	coalesce(p.bio, '') AS bio
FROM auth_user u
LEFT JOIN profile_stats p ON p.user_id = u.user_registered_id
WHERE u.id = ?1 OR u.user_registered_id = ?1
    `

	ps := &UserByIdorRegisteredIdStmt{
		conn:      tx,
		querySQL:  querySQL,
		hasSlices: false,
	}

	if !ps.hasSlices {
		ps.stmt = tx.Prep(querySQL)
	}

	return ps
}

func (ps *UserByIdorRegisteredIdStmt) Run(
	id string,
) (
	res *UserByIdorRegisteredIdRes,
	err error,
) {
	querySQL := ps.querySQL

	var stmt *sqlite.Stmt
	if ps.hasSlices {
		stmt = ps.conn.Prep(querySQL)
	} else {
		stmt = ps.stmt
	}

	defer func() {
		_ = stmt.ClearBindings()
		_ = stmt.Reset()
	}()

	bindIndex := 1
	// Bind parameters
	stmt.BindText(bindIndex, id)

	bindIndex++

	// Execute the query
	if hasRow, err := stmt.Step(); err != nil {
		return res, fmt.Errorf("failed to execute {{.Name.Lower}} SQL: %w", err)
	} else if hasRow {
		row := UserByIdorRegisteredIdRes{}
		row.Id = stmt.ColumnText(0)
		row.UserRegisteredId = stmt.ColumnText(1)
		row.Email = stmt.ColumnText(2)
		row.Username = stmt.ColumnText(3)
		row.Avatar = stmt.ColumnText(4)
		row.Bio = stmt.ColumnText(5)
		res = &row
	}

	return res, nil
}

func OnceUserByIdorRegisteredId(
	tx *sqlite.Conn,
	id string,
) (
	res *UserByIdorRegisteredIdRes,
	err error,
) {
	ps := UserByIdorRegisteredId(tx)

	return ps.Run(
		id,
	)
}
